
name: Build Android

on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64", "x86_64" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Environment
        run: |
          sudo apt update
          sudo apt install -y libxrandr-dev libxxf86vm-dev libxcb-*-dev libx11-xcb-dev libxfixes-dev libdrm-dev libx11-dev
          pip3 install mako meson ninja

      - name: Set ndkver,sdkver and work_dir
        run: |
          echo "NDK_VER=android-ndk-r27c" >> $GITHUB_ENV
          echo "SDK_VER=24" >> $GITHUB_ENV
          echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Download and extract NDK
        run: |
          echo "Downloading android-ndk from google server ..."
          curl https://dl.google.com/android/repository/${NDK_VER}-linux.zip --output ${NDK_VER}-linux.zip &> /dev/null
          echo "Extracting android-ndk to a folder ..."
          unzip ${NDK_VER}-linux.zip &> /dev/null

      - name: Build
        run: |
          envsubst <android-${{matrix.arch}} >build-crossfile
          meson "build-android" \
            --prefix=/tmp/zink \
            --cross-file "build-crossfile" \
            --buildtype debug \
            -Dplatforms=android \
            -Dplatform-sdk-version=24 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dgbm=disabled \
            -Dglx=dri \
            -Dglx-direct=true \
            -Dopengl=true \
            -Dosmesa=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=virgl \
            -Dshared-glapi=false
          ninja -C "build-android" install
          cp /tmp/zink/lib/libOSMesa.so.8.0.0 /tmp/zink/lib/libOSMesa.so.8
      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: libOSMesa_${{matrix.arch}}
          path: /tmp/zink/lib/libOSMesa.so.8
